### ISSUE TITLE
NameError: name 'robot_x' is not defined, No /odom topic publisher?

### ISSUE THREAD

**Issue by YJingMAX** [yabdulra/Trajectory-tracking-with-obstacle-avoidance#1]
$ roslaunch trajectory_tracking main.launch

SUMMARY
========

PARAMETERS
 * /circular/center_x: 0
 * /circular/center_y: 0
 * /circular/path: /home/yang/ros_ws...
 * /circular/period: 150
 * /circular/radius: 3
 * /robot/path: /home/yang/ros_ws...
 * /robot/robot_radius: 0.089
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    circular (trajectory_tracking/circular)
    robot (trajectory_tracking/tracking_controller)
  /circular/
    plotter (trajectory_tracking/plotter.py)

auto-starting new master
process[master]: started with pid [37521]
ROS_MASTER_URI=http://192.168.1.100:11311

setting /run_id to 21d27688-591a-11ed-8c2b-757046a668aa
process[rosout-1]: started with pid [37546]
started core service [/rosout]
process[circular/plotter-2]: started with pid [37553]
process[circular-3]: started with pid [37554]
process[robot-4]: started with pid [37555]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 216, in process
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 953, in _start
    self._init_draw()
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1732, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1755, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/home/yang/ros_ws/src/github/Trajectory_tracking/trajectory_tracking/scripts/plotter.py", line 62, in animate1
    xrobot.append(float(robot_x))
NameError: name 'robot_x' is not defined

**Comment by YJingMAX** [comment]
Is no /odom topic publisher?
Any help would be appreciated! Thank you

**Comment by yabdulra** [comment]
Have you checked if your robot is publishing its odometry on `/odom` topic?
`robot_x` is not defined because the plotter isn't getting any message from a topic called `/odom`.
If your robot's odom topic isn't `/odom`, then consider remapping the topic the plotter is subscribing to from `/odom` to your robot's odom topic by adding `<remap from="/odom" to="your robot odom" />` just after line 5 of the main.launch file.
Note: remember to change `"your robot odom"` to the appropriate odom topic of your robot.
